language: cpp
sudo: false
skip_cleanup: true

matrix:
  include:
    - os: linux
      env: LLVM_VERSION=7.0.0
      addons: { apt: { packages: ["clang-7"], sources: ["llvm-toolchain-trusty-7", "ubuntu-toolchain-r-test"] } }

    - os: linux
      env: LLVM_VERSION=8.0.0
      addons: { apt: { packages: ["clang-8"], sources: ["llvm-toolchain-trusty-8", "ubuntu-toolchain-r-test"] } }

    - os: linux
      env: COMPILER=g++-5
      addons: { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }

    - os: linux
      env: COMPILER=g++-6
      addons: { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }

    - os: linux
      env: COMPILER=g++-7
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    - os: linux
      env: COMPILER=g++-8
      addons: { apt: { packages: ["g++-8"], sources: ["ubuntu-toolchain-r-test"] } }

install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  ############################################################################
  # Pick up the overriden compiler if any
  ############################################################################
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${LLVM_VERSION}" != "" ]]; then export CXX="clang++-${LLVM_VERSION%.[0-9].[0-9]}"; fi
  - if [[ "${LLVM_VERSION}" != "" ]]; then export COMPILER="clang++-${LLVM_VERSION%.[0-9].[0-9]}"; fi
  - ${CXX} --version

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.10.0
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake || brew upgrade cmake
    fi
  - cmake --version


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - (mkdir build && cd build && cmake ..)

script:
  - cmake --build build
  - cd build
  - mkdir results
  - ctest . > results/log.txt
  - cd results
  - rm -rfv ~/.dropbox_uploader
  - echo "OAUTH_ACCESS_TOKEN=$OAUTH_ACCESS_TOKEN" > ~/.dropbox_uploader
  - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o ~/dropbox_uploader.sh
  - chmod +x ~/dropbox_uploader.sh
  - python ../../src/parse.py > table.txt
  - cat table.txt
  - ~/dropbox_uploader.sh upload table.txt Public/ConformanceTest/$TRAVIS_BRANCH/$COMPILER/table.txt
